# Generated by Django 4.2.30 on 2026-07-20 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_archived_at_property_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacated_at', models.DateField()),
                ('occupied_at', models.DateField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancy_periods', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Vacancy Period',
                'verbose_name_plural': 'Vacancy Periods',
                'ordering': ['-vacated_at'],
                'indexes': [models.Index(fields=['unit', 'occupied_at'], name='vacancy_vac_unit_id_7e7d56_idx')],
            },
        ),
    ]
