# Generated by Django 4.2.30 on 2026-07-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
