# Generated by Django 4.2.30 on 2026-07-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
