# Generated by Django 4.2.30 on 2026-07-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='renewed_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewed_to', to='leases.lease'),
        ),
    ]
