# Generated by Django 4.2.30 on 2026-07-17 07:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_archived_at_property_is_archived_and_more'),
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], db_index=True, default='ACTIVE', max_length=20)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='occupancy', to='leases.lease')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Occupancy',
                'verbose_name_plural': 'Occupancies',
                'ordering': ['-move_in_date'],
                'indexes': [models.Index(fields=['unit', 'status'], name='occupancy_o_unit_id_866d0f_idx'), models.Index(fields=['status'], name='occupancy_o_status_8736b7_idx')],
            },
        ),
    ]
